kind: pipeline
type: kubernetes
name: webbase
steps:
  - name: test-node-12
    image: node:12
    commands:
      - yarn
      - yarn lint
      - yarn build
  - name: docker
    image: plugins/docker
    repo: minskylab/webbase
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
